version: '3.11.0'

services:
  db:
    container_name: 'booking_db'
    image: postgres:16

    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - booking_network
    volumes:
      - pg-booking-data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: 'booking_backend'
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always

    depends_on:
      - db
    networks:
      - booking_network
    env_file:
      - .env

  nginx:
    container_name: 'booking_nginx'
    image: nginx:latest
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - static_value:/var/html/static/
    depends_on:
      - web
    networks:
      - booking_network

  cache:
    container_name: 'booking_cache'
    image: redis:7.4
    ports:
      - '7379:6379'
    networks:
      - booking_network

networks:
  booking_network:
    external: true

volumes:
  pg-booking-data:
  static_value:
