version: '3.11.0'

services:
  db:
    container_name: 'booking_db'
    image: postgres:16

    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - booking_network
    volumes:
      - pg-booking-data:/var/lib/postgresql/data

  web:
    container_name: 'booking_backend'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7777:8000"
    restart: always

    depends_on:
      - db
    networks:
      - booking_network
    env_file:
      - .env

  cache:
    container_name: 'booking_cache'
    image: redis:7.4
    ports:
      - '7379:6379'
    networks:
      - booking_network


networks:
  booking_network:
    external: true

volumes:
  pg-booking-data:
