"""ondelete set null for image field of hotel model

Revision ID: 08
Revises: 07
Create Date: 2024-11-10 17:42:42.098990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08"
down_revision: Union[str, None] = "07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint(
        "hotelsmodel_image_fkey", "hotelsmodel", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "hotelsmodel",
        "imagesmodel",
        ["image"],
        ["id"],
        ondelete="set null",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotelsmodel", type_="foreignkey")
    op.create_foreign_key(
        "hotelsmodel_image_fkey",
        "hotelsmodel",
        "imagesmodel",
        ["image"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
